[package]
name = "pegasus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
thiserror = { version = "1.0.30" }

[dev-dependencies]
boot-core.workspace = true
cw-multi-test.workspace = true
