/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  bundle_limit: number;
  maintainer: string;
  max_offers: number;
  offer_expiry: ExpiryRange;
}
export interface ExpiryRange {
  max: number;
  min: number;
}
export type ExecuteMsg = {
  create_offer: {
    expires_at?: Timestamp | null;
    message?: string | null;
    offered_balances: Coin[];
    offered_nfts: TokenMsg[];
    peer: string;
    wanted_nfts: TokenMsg[];
  };
} | {
  remove_offer: {
    id: number;
  };
} | {
  accept_offer: {
    id: number;
  };
} | {
  reject_offer: {
    id: number;
  };
} | {
  remove_stale_offer: {
    id: number;
  };
};
export type Timestamp = Uint64;
export type Uint64 = string;
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface TokenMsg {
  collection: string;
  token_id: number;
}
export type QueryMsg = {
  offer: {
    id: number;
  };
} | {
  offers_by_sender: {
    sender: string;
  };
} | {
  offers_by_peer: {
    peer: string;
  };
} | {
  params: {};
};
export type SudoMsg = {
  update_params: {
    bundle_limit?: number | null;
    maintainer?: string | null;
    max_offers?: number | null;
    offer_expiry?: ExpiryRange | null;
  };
};
export type Addr = string;
export interface OfferResponse {
  offer?: Offer | null;
}
export interface Offer {
  created_at: Timestamp;
  expires_at: Timestamp;
  id: number;
  message?: string | null;
  offered_balances: Coin[];
  offered_nfts: Token[];
  peer: Addr;
  royalties: Royalty[];
  sender: Addr;
  wanted_nfts: Token[];
}
export interface Token {
  collection: Addr;
  token_id: number;
}
export interface Royalty {
  amount: Coin;
  creator: Addr;
}
export interface OffersResponse {
  offers: Offer[];
}
export interface ParamsResponse {
  params: SudoParams;
}
export interface SudoParams {
  bundle_limit: number;
  maintainer: Addr;
  max_offers: number;
  offer_expiry: ExpiryRange;
}