/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { ExecuteMsg, Timestamp, Uint64, TokenMsg, InstantiateMsg, ExpiryRange, Addr, OfferResponse, Offer, Token, OffersResponse, ParamsResponse, SudoParams, QueryMsg } from "./Pegasus.types";
export interface PegasusMsg {
  contractAddress: string;
  sender: string;
  createOffer: ({
    expiresAt,
    offeredNfts,
    peer,
    wantedNfts
  }: {
    expiresAt?: Timestamp;
    offeredNfts: TokenMsg[];
    peer: string;
    wantedNfts: TokenMsg[];
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeOffer: ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  acceptOffer: ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  rejectOffer: ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  removeStaleOffer: ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class PegasusMsgComposer implements PegasusMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createOffer = this.createOffer.bind(this);
    this.removeOffer = this.removeOffer.bind(this);
    this.acceptOffer = this.acceptOffer.bind(this);
    this.rejectOffer = this.rejectOffer.bind(this);
    this.removeStaleOffer = this.removeStaleOffer.bind(this);
  }
  createOffer = ({
    expiresAt,
    offeredNfts,
    peer,
    wantedNfts
  }: {
    expiresAt?: Timestamp;
    offeredNfts: TokenMsg[];
    peer: string;
    wantedNfts: TokenMsg[];
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_offer: {
            expires_at: expiresAt,
            offered_nfts: offeredNfts,
            peer,
            wanted_nfts: wantedNfts
          }
        })),
        funds: _funds
      })
    };
  };
  removeOffer = ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_offer: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
  acceptOffer = ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          accept_offer: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
  rejectOffer = ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          reject_offer: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
  removeStaleOffer = ({
    id
  }: {
    id: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          remove_stale_offer: {
            id
          }
        })),
        funds: _funds
      })
    };
  };
}