[package]
name = "pegasus-boot"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
boot-core = { workspace = true }
pegasus = { path = "../pegasus" }
cw721 = { workspace = true }
cw721-base = { workspace = true }
sg721 = { workspace = true }
