on:
  release:
    types: [created]

name: Release

jobs:
  release:
    name: Release wasm32-unknown-unknown
    runs-on: ubuntu-latest
    steps:
      - name: Optimize workspace
        run: |
          rustup target add wasm32-unknown-unknown;
          docker run --rm -v "$(pwd)":/code \
            --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
            --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
            cosmwasm/rust-optimizer:0.12.6;
      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: pegasus
          path: artifacts/
          if-no-files-found: error
